baseURL = "https://zt.dev/"
languageCode = "en-us"
title = "zt.dev - Zero-Trust Development"
copyright = "zt.dev authors"


[languages]
  [languages.en]
    title = "zt.dev - Zero Trust and Software Supply Chain Defense"
    subtitle = "Zero Trust, Software, Identity, Policy, Control, Automation"


  [languages.en.params.logo]
    logoUser = "frederick"
    logoHost = "zt.dev"


  [langues.en.menu]
  [[languages.en.menu.main]]
    identifier = "zero-trust"
    name = "zero-trust"
    url = "/zero-trust"

  [[languages.en.menu.main]]
    identifier = "sbom"
    name = "sbom"
    url = "/sbom"

  [[languages.en.menu.main]]
    identifier = "talks" 
    name = "talks"
    url = "/talks"
